version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      
      - run:
          name: Nombre
          command: echo Carlos
      - run:
          name: Apellido
          command: echo Dolz
